'''
Exercise 19: Cows and Bulls

Create a program that will play the “cows and bulls” game with the user.
The game works like this:

Randomly generate a 4-digit number.
Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place,
they have a “cow”. For every digit the user guessed correctly in the
wrong place is a “bull.”
Every time the user makes a guess, tell them how many
“cows” and “bulls” they have.
Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout
the game and tell the user at the end.

Say the number generated by the computer is 1038.
An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
  
Until the user guesses the number.
'''

import random

def user_guess():
    user_input = input("Enter a number: \n")
    return user_input

def generate_number(digits):
    random_str = ""
    for i in range(digits):  
        random_str = random_str + str(random.randint(0,9))
    random_number = random_str
    return random_number

def cows_and_bulls():
    print("Welcome to the Cows and Bulls Game!")
    print("How many digits would you like the number you guess to have? \n")
    user_digits = int(user_guess())
    ntg = generate_number(user_digits)
    counter = 0
    guessed_it = 0
    while guessed_it == 0:
        digit_reminder = "Remember the number is " + str(user_digits) + " digits. \n"
        print(digit_reminder)
        print("What's your guess? \n")
        proper_guess = 0
        while proper_guess == 0:
            un = user_guess()
            if len(un) != user_digits:
                print("Hey now, your guess had the wrong number of digits! Try again.")
            elif len(un) == user_digits:
                proper_guess = 1
            cow_counter = 0
            bull_counter = 0
            temp_ntg = list(ntg)
            temp_un = list(un)
        for i in range(user_digits):
            if ntg[i] == un[i]:
                cow_counter = cow_counter + 1
                temp_ntg[i] = ''
                temp_un[i] = ''
        stntg = ''.join(temp_ntg)
        sttun = ''.join(temp_un)
        temp_ntg = list(stntg)
        temp_un = list(sttun)
        for i in sttun:
            if i in stntg:
                bull_counter = bull_counter + 1
                str_temp_ntg = ''.join(temp_ntg)
                str_temp_ntg = str_temp_ntg.replace(i,'',1)
                stntg = str_temp_ntg
                temp_ntg = list(str_temp_ntg)
        cont_message = str(cow_counter) + " cows, " + str(bull_counter) + " bulls \n"
        win_message = "Yee-haw! You won 'pardner! The number was " + ntg + ". It only took you " + str(counter+1) + " guesses!"
        if cow_counter == user_digits:
            print(win_message)
            guessed_it = 1
        else:
            print(cont_message)
            counter = counter + 1
    
if __name__ == "__main__":
    a = cows_and_bulls()
    
